---
- name: Configure OSPF on R2 and R3
  hosts: routers
  gather_facts: false
  tasks:
    - name: Configure OSPF on R2
      ios_config:
        lines:
          - router ospf 1
          - network 192.168.2.0 0.0.0.3 area 0
          - network 192.168.4.0 0.0.0.3 area 0
        provider:
          host: "{{ inventory_hostname }}"
          username: <username>
          password: <password>
    - name: Configure OSPF on R3
      ios_config:
        lines:
          - router ospf 1
          - network 192.168.4.0 0.0.0.3 area 0
          - network 192.168.77.0 0.0.0.255 area 0
        provider:
          host: "{{ inventory_hostname }}"
          username: username
          password: password
